import Image from "next/image";
import Link from "next/link";
import "../styles/globals.css";

export const metadata = {
  title: "Jack's Blog" ,
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const header = (
      <header>
        <div className="text-center bg-slate-800 p-8 my-6 rounded-md">
          <Image alt="logo" src="/logo.png" width={40} height={40} className="mx-auto"/>
          <Link href="/">
            <h1 className="text-2xl text-white font-bold mt-4" >Jacks's Blog</h1>
          </Link>
          <p className="text-slate-300">🤟 Welcome to my tech blog. 💻</p>
        </div>
      </header>

  );

  const footer = (
    <footer>
      <div className="border-t border-slate-500 mt-12 py-6 text-center text-slate-400">
        <h3>Developed by Pixegami</h3>
      </div>
    </footer>
  )


  return (
    <html lang="en">
      <body>
        <div className="mx-auto  max-w-2xl px-6">
          {header}
          {children}
          {footer}
        </div>
        
      </body>
    </html>
  )
}
